version: '3'
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
    command: /bin/bash -c "a2enmod rewrite && apache2-foreground"